// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVkp2lUbkVkJHe7fpUnFokOgeQ-fxeJtc',
    appId: '1:824204033260:web:d1506c4584b25c5d6f79c9',
    messagingSenderId: '824204033260',
    projectId: 'basic-3591b',
    authDomain: 'basic-3591b.firebaseapp.com',
    storageBucket: 'basic-3591b.firebasestorage.app',
    measurementId: 'G-DS9HNRV78S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2ECNtg-7FE2tmLcMeCNmlrVjoFP8Gbzk',
    appId: '1:824204033260:android:95c2694abf165f0d6f79c9',
    messagingSenderId: '824204033260',
    projectId: 'basic-3591b',
    storageBucket: 'basic-3591b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClpUzlYOzYQzWL6UYND7BUa-_ZZr855bk',
    appId: '1:824204033260:ios:0d03fafc6be1c5ee6f79c9',
    messagingSenderId: '824204033260',
    projectId: 'basic-3591b',
    storageBucket: 'basic-3591b.firebasestorage.app',
    iosBundleId: 'com.example.basicApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClpUzlYOzYQzWL6UYND7BUa-_ZZr855bk',
    appId: '1:824204033260:ios:0d03fafc6be1c5ee6f79c9',
    messagingSenderId: '824204033260',
    projectId: 'basic-3591b',
    storageBucket: 'basic-3591b.firebasestorage.app',
    iosBundleId: 'com.example.basicApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVkp2lUbkVkJHe7fpUnFokOgeQ-fxeJtc',
    appId: '1:824204033260:web:24a331b72f05bf266f79c9',
    messagingSenderId: '824204033260',
    projectId: 'basic-3591b',
    authDomain: 'basic-3591b.firebaseapp.com',
    storageBucket: 'basic-3591b.firebasestorage.app',
    measurementId: 'G-PV0MRE9S5J',
  );

}