// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAM7hGVvv24NFxnwG8rlt8g8KZjS2_XRr0',
    appId: '1:343756330705:web:199a10fd330f76302dd7f0',
    messagingSenderId: '343756330705',
    projectId: 'basic-2bb91',
    authDomain: 'basic-2bb91.firebaseapp.com',
    storageBucket: 'basic-2bb91.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDp0bB9_L7CHb0IW_6BjdNMmMu1-TSNH3U',
    appId: '1:343756330705:android:d63cb8b613640eb82dd7f0',
    messagingSenderId: '343756330705',
    projectId: 'basic-2bb91',
    storageBucket: 'basic-2bb91.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJoKWg1OXAX0SIkPCS0EsjUK3mHRaWJM0',
    appId: '1:343756330705:ios:380cf3cef5af85a12dd7f0',
    messagingSenderId: '343756330705',
    projectId: 'basic-2bb91',
    storageBucket: 'basic-2bb91.appspot.com',
    iosBundleId: 'com.example.basicApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJoKWg1OXAX0SIkPCS0EsjUK3mHRaWJM0',
    appId: '1:343756330705:ios:380cf3cef5af85a12dd7f0',
    messagingSenderId: '343756330705',
    projectId: 'basic-2bb91',
    storageBucket: 'basic-2bb91.appspot.com',
    iosBundleId: 'com.example.basicApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAM7hGVvv24NFxnwG8rlt8g8KZjS2_XRr0',
    appId: '1:343756330705:web:a29123b5910c02fb2dd7f0',
    messagingSenderId: '343756330705',
    projectId: 'basic-2bb91',
    authDomain: 'basic-2bb91.firebaseapp.com',
    storageBucket: 'basic-2bb91.appspot.com',
  );
}
